#配置文件版本号 请勿修改
Version: 1.0

#格式列表
Formats:
  #格式名称 对应当前文件夹下的default.yml
  default: 
    #优先级(将按照从小到大依次检测 比如 1-50 优先检测 1 符合则显示 不符合 检测 2 ...)
    index: 50
    #权限
    permission: 'MiaoChat.default'
    #范围(0为无限制)
    range: 0
    #解析物品(%i=>手上物品,%0-9快捷栏对应物品)
    item: true
    #物品解析规则
    itemformat: '&6[&b%s&6]&r'
  #格式名称 对应当前文件夹下的admin.yml
  admin: 
    #优先级(将按照从小到大依次检测 比如 1-50 优先检测 1 符合则显示 不符合 检测 2 ...)
    index: 49
    #权限
    permission: 'MiaoChat.admin'
    #范围(0为无限制)
    range: 0
    #解析物品(%i=>手上物品,%0-9快捷栏对应物品)
    item: true
    #物品解析规则
    itemformat: '&6[&b%s&6]&r'