#格式化配置
Format:
  #前缀配置 于玩家名称前
  Prefix: 
    #顺序
    1:
      #文本 支持PAPI变量
      text: '&6[&a%player_world%&6]'
      #悬浮提示 支持PAPI
      tip: 
      - '&6当前所在位置:'
      - '&6世界: &d%player_world%'
      - '&6坐标: &aX:%player_x% Y: %player_y% Z: %player_z%'
      - ''
      - '&c点击即可TP我!'
      #点击操作
      click:
        #操作类型: [COMMAND,SUGGEST] 
        #COMMAND代表执行命令
        #SUGGEST代表命令补全
        type: 'COMMAND'
        #命令 支持PAPI
        command: '/tpa %player_name%'
#    可以添加多个
#    2:
#      #文本 支持PAPI变量
#      text: '&6[&a%player_world%&6]'
#      #悬浮提示 支持PAPI
#      tip: []
  #玩家名称配置
  Player: 
    text: '&b%player_name% '
    tip: 
    - '&6玩家名称: &b%player_name%'
    - '&6玩家等级: &a%player_level%'
    - '&6玩家血量: &c%player_health%'
    - '&6玩家饥饿: &d%player_food_level%'
    - '&6游戏模式: &4%player_gamemode%'
    - ''
    - '&c点击与我聊天'
    click: 
      type: 'SUGGEST'
      command: '/tell %player_name%'
#后缀配置 于玩家名称后 由于一般没人用 我注释掉了
#  Suffix: 
#    1:
#      text: '[变量1]'
#      tip: 
#      - '变量1提示'
#      click: 
#        type: 'COMMAND'
#        command: 'say 命令执行'
#    同样可以添加多个
#    2: