name: ${project.artifactId}
description: ${project.description}
main: ${project.groupId}.${project.artifactId}.${project.artifactId}
version: ${project.version}-git-${env.GIT_COMMIT}
author: 喵♂呜
website: ${ciManagement.url}
depend:
- PlaceholderAPI
commands:
  ${project.artifactId}:
    description: ${project.artifactId} - ${project.description}
    aliases:
    - mct
    - mchat
    usage: §b使用/${project.artifactId} help 查看帮助!
    permission: ${project.artifactId}.default
    permission-message: §c你没有 <permission> 的权限来执行此命令!
permissions:
  ${project.artifactId}.default:
    description: 默认格式权限!
    default: true
  ${project.artifactId}.toggle:
    description: 开启关闭聊天!
    default: true
  ${project.artifactId}.color:
    description: 彩字聊天权限!
    default: true
  ${project.artifactId}.admin:
    description: 管理员格式权限!
    default: op
  ${project.artifactId}.reload:
    description: 重新载入插件!
    default: op